/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- ====================================================================== 
-- 5) Magnitude
-- ======================================================================

-- Find total customers by countries
SELECT
	country,
    COUNT(customer_key) AS total_customers
FROM datawarehouseanalytics.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
	gender,
    COUNT(gender) AS total_customers
FROM datawarehouseanalytics.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT 
	category,
    count(product_key) AS total_products
FROM datawarehouseanalytics.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
	category, 
    AVG(cost) AS avg_costs
    FROM datawarehouseanalytics.dim_products
    GROUP BY category
    ORDER BY avg_costs DESC;

-- What is the total revenue generated for each categary?
SELECT 
	p.category,
    SUM(f.sales_amount) AS total_revenue
FROM datawarehouseanalytics.fact_sales AS f
LEFT JOIN datawarehouseanalytics.dim_products p
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find total revenue is generated by each customer
SELECT
	c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM datawarehouseanalytics.fact_sales AS f
LEFT JOIN datawarehouseanalytics.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY 
	c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
	c.country,
    SUM(f.quantity) AS total_sold_items
FROM datawarehouseanalytics.fact_sales AS f
LEFT JOIN datawarehouseanalytics.dim_customers c
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;

